{% set name = "alibabacloud-tea-util" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_tea_util-{{ version }}.tar.gz
  sha256: 72a2f5a046e5b977ade4202eb4f65b3d70ad707a548e29aacd4a572c2d18d06b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - alibabacloud-tea >=0.3.3

test:
  imports:
    - alibabacloud_tea_util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aliyun/tea-util/tree/master/python
  summary: The tea-util module of alibabaCloud Python SDK.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
