{% set name = "alibabacloud-tea-util" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/alibabacloud_tea_util-{{ version }}.tar.gz
  sha256: f68231e36ccd788ccf3b8d72d67bf76a0fa8f5b7a5f01489484a1f133b448f71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - alibabacloud-tea >=0.3.3

test:
  imports:
    - alibabacloud_tea_util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aliyun/tea-util/tree/master/python
  summary: The tea-util module of alibabaCloud Python SDK.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
